### ISSUE TITLE
Release the v1.0.0

### ISSUE THREAD

**Issue by GuillaumeAmat** [osmlab/osm-request#15]
And make rid of the _heavy development_ warning in the README file. What do you think about that @PanierAvide? :)

**Comment by PanierAvide** [comment]
If it was only me, I would keep the warning and 0.x version until we have a more complete code testing and coverage. I had some surprises using functions I wasn't using before and unexpected behaviour. For example I haven't tested in a real project user preferences methods and can't be sure of their behaviour. And also improve documentation and give more practical examples.

**Comment by PanierAvide** [comment]
Closing as in between there was a 1.x and 2.x release :grin:
